server:
  port: 8123
spring:
  application:
    name: travel-app-internal-api
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
        application: ${spring.application.name}
travel:
  app:
    base-url: "http://localhost:8123"
